### PR TITLE
Replace Aid::new with Aid::try_new

### LINKED ISSUE #7: Panic on Select command with an invalid Aid.
Hi!

A bit of fuzzing this library found that a panic happens when `apdu_dispatch` receives a select command with an Aid in the data field that is incorrect. This is because [Aid::new](https://docs.rs/iso7816/0.1.0/iso7816/aid/struct.Aid.html#method.new) panics when the input data is invalid.

### PR DESCRIPTION
**Pull request by sosthene-nitrokey**
Fixes #7

### CODE REVIEW

File: src/dispatch.rs [hunk 1]
```diff
@@ -94,8 +94,7 @@ impl ApduDispatch
     fn apdu_type<const S: usize>(apdu: &iso7816::Command<S>) -> RequestType {
         info!("instruction: {:?} {}", apdu.instruction(), apdu.p1);
         if apdu.instruction() == Instruction::Select && (apdu.p1 & 0x04) != 0 {
-            // RequestType::Select(Aid::try_from_slice(apdu.data()).unwrap())
-            RequestType::Select(Aid::new(apdu.data()))
+            Aid::try_new(&apdu.data()).map_or(RequestType::NewCommand, RequestType::Select)
```
Comment (robin-nitrokey) [inline src/dispatch.rs:97]: What do you think about returning `None` instead of `NewCommand`?  I don’t think we should pass a request with an invalid AID to the app.

Comment (sosthene-nitrokey) [reply src/dispatch.rs:97]: Why not. I think this should be logged in any case.

I'll make it `None` and add a `warn!` log.

Comment (sosthene-nitrokey) [reply src/dispatch.rs]: Ok, I fixed it by adding a `BadCommand` request type that makes the dispatch return an error

File: tests/dispatch.rs [hunk 2]
```diff
@@ -307,6 +307,17 @@ fn select_not_found() {
     ])
 }
 
+#[test]
+#[serial]
+fn select_bad_aid() {
+    // Sending a select after chaining 0 bytes should result in successful select operation
```
Comment (robin-nitrokey) [inline tests/dispatch.rs:313]: Outdated comment?

**Review by robin-nitrokey — APPROVED** [review]
